# Generated by Django 4.2.5 on 2023-09-13 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performer', models.CharField(max_length=60)),
                ('tickets_count', models.IntegerField()),
                ('date', models.DateField()),
                ('place', models.CharField(max_length=256)),
                ('concert_type', models.CharField(choices=[('CM', 'Classical Music'), ('OA', 'Open Air'), ('P', 'Party')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='OpenAir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directions', models.TextField()),
                ('headliner', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='ClassicMusic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice_type', models.CharField(choices=[('A', 'Alt'), ('T', 'Tenor'), ('B', 'Bas')], max_length=1)),
                ('name', models.CharField(max_length=256)),
                ('composer', models.CharField(max_length=50)),
                ('concert_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concerts.concert')),
            ],
        ),
    ]
