# Generated by Django 4.2.5 on 2023-11-09 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='image',
            field=models.TextField(default='default.jpg'),
        ),
    ]
