# Generated by Django 4.2.5 on 2023-09-13 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_limit', models.IntegerField()),
                ('concert_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concerts.concert')),
            ],
        ),
    ]
