# Generated by Django 4.2.5 on 2024-01-22 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0002_alter_concert_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classicmusic',
            name='concert_id',
        ),
        migrations.RemoveField(
            model_name='classicmusic',
            name='id',
        ),
        migrations.RemoveField(
            model_name='classicmusic',
            name='name',
        ),
        migrations.RemoveField(
            model_name='concert',
            name='concert_type',
        ),
        migrations.RemoveField(
            model_name='openair',
            name='concert_id',
        ),
        migrations.RemoveField(
            model_name='openair',
            name='id',
        ),
        migrations.RemoveField(
            model_name='party',
            name='concert_id',
        ),
        migrations.RemoveField(
            model_name='party',
            name='id',
        ),
        migrations.AddField(
            model_name='classicmusic',
            name='concert_ptr',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='concerts.concert'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='openair',
            name='concert_ptr',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='concerts.concert'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='party',
            name='concert_ptr',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='concerts.concert'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='concert',
            name='image',
            field=models.TextField(),
        ),
    ]
