# Generated by Django 4.2.5 on 2023-09-15 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0002_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='openair',
            name='concert_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='concerts.concert'),
            preserve_default=False,
        ),
    ]
