# Generated by Django 4.2.5 on 2023-12-08 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0002_alter_concert_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='image',
            field=models.TextField(),
        ),
    ]
