# Generated by Django 4.2.5 on 2023-09-19 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0003_openair_concert_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='name',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='concert',
            name='price',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
    ]
