# Generated by Django 4.2.5 on 2024-01-22 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0003_alter_concert_image'),
        ('concerts', '0003_remove_classicmusic_concert_id_and_more'),
    ]

    operations = [
    ]
