# Generated by Django 4.2.5 on 2023-10-05 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0004_concert_name_concert_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='description',
            field=models.TextField(default='Описание концерта'),
        ),
        migrations.AddField(
            model_name='concert',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='concerts/'),
        ),
    ]
