# Generated by Django 4.2.5 on 2023-09-12 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('mail', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=5)),
            ],
        ),
    ]
