# Generated by Django 4.2.5 on 2023-09-18 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promocodes', '0001_initial'),
        ('concerts', '0003_openair_concert_id'),
        ('users', '0001_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transection',
            new_name='Transaction',
        ),
    ]
